FROM node:8.9
MAINTAINER hans@webmapper.net
RUN apt-get update && apt-get install -yq git
WORKDIR /app
COPY build-nlmaps.sh build-nlmaps.sh
COPY config/amsterdam.config.js amsterdam.config.js
CMD sh build-nlmaps.sh
