FROM node:8.9
MAINTAINER hans@webmapper.net
RUN apt-get update && apt-get install -yq git
WORKDIR /app
COPY package.json /app/package.json
RUN npm install
COPY scripts /app/scripts/
RUN mkdir /app/test
COPY test/index.html /app/test/index.html
COPY test/browser-test.js /app/test/browser-test.js
COPY config/amsterdam.config.js config/amsterdam.config.js
RUN npm run nlmaps
