FROM node:8.9
MAINTAINER hans@webmapper.net
RUN apt-get update && apt-get install -yq git
WORKDIR /app
COPY package.json /app/package.json
COPY scripts /app/scripts/
COPY config/amsterdam.config.js config/amsterdam.config.js
RUN npm run nlmaps
